name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'static/**'
      - '**.md'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  flutter_build_ohos:
    name: Release for ohos
    runs-on: ubuntu-latest
    permissions: write-all
    container: ghcr.io/sanchuanhehe/harmony-next-pipeline-docker/harmonyos-ci-image:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl xz-utils zip libglu1-mesa
        shell: bash 
      - name: Build Flutter for ohos
        run: |
          git clone https://gitcode.com/openharmony-tpc/flutter_flutter.git $GITHUB_WORKSPACE/flutter
          cd flutter
          git switch oh-3.27.4-dev
          git pull origin
          cd ..
          
          export PATH=$GITHUB_WORKSPACE/flutter/bin:$PATH
          export PATH=/opt/harmonyos-tools/command-line-tools/ohpm/bin:$PATH
          export PATH=/opt/harmonyos-tools/command-line-tools/hvigor/bin:$PATH
          export PATH=/opt/harmonyos-tools/command-line-tools/tool/node/bin:$PATH
          export PATH=/opt/harmonyos-tools/command-line-tools/bin:$PATH
          export OHOS_NDK_HOME=/opt/harmonyos-tools/command-line-tools/sdk/default/openharmony

          flutter doctor -v
          flutter pub get
          flutter build hap --release
        shell: bash
      - name: Package ohos build output
        run: cp ./ohos/entry/build/default/outputs/default/entry-default-unsigned.hap Kazumi_ohos_canary.hap
        shell: bash
      - name: Upload ohos outputs
        uses: actions/upload-artifact@v4
        with:
          name: ohos_outputs
          path: Kazumi_ohos_*.hap
