name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'static/**'
      - '**.md'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  flutter_build_ohos:
    name: Release for ohos
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils zip libglu1-mesa
        shell: bash
      - name: Setup HarmonyOS toolchain
        run: |
          echo Downloading sdk...
          curl -fsSL https://github.com/ErBWs/ohos-sdk/releases/download/5.0.13.200/ohos-sdk-linux-amd64.tar.gz.aa -o ohos-sdk-linux-amd64.tar.gz.aa
          curl -fsSL https://github.com/ErBWs/ohos-sdk/releases/download/5.0.13.200/ohos-sdk-linux-amd64.tar.gz.ab -o ohos-sdk-linux-amd64.tar.gz.ab
          curl -fsSL https://github.com/ErBWs/ohos-sdk/releases/download/5.0.13.200/ohos-sdk-linux-amd64.tar.gz.sha256 -o ohos-sdk-linux-amd64.tar.gz.sha256
          cat ohos-sdk-linux-amd64.tar.gz.aa ohos-sdk-linux-amd64.tar.gz.ab > ohos-sdk-linux-amd64.tar.gz
          sha256sum -c ohos-sdk-linux-amd64.tar.gz.sha256

          echo Extracting sdk...
          tar -xzf ohos-sdk-linux-amd64.tar.gz
          rm ohos-sdk-linux-amd64.tar.*

          echo "OHOS_BASE_SDK_HOME=$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony" >> "$GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/command-line-tools/tool/node/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/command-line-tools/bin" >> $GITHUB_PATH
        shell: bash
      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup flutter-ohos
        run: |
          git clone https://gitcode.com/openharmony-tpc/flutter_flutter.git $GITHUB_WORKSPACE/flutter
          cd flutter
          git switch oh-3.27.4-dev
          git pull origin
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        shell: bash
      - name: Print Flutter version
        run: flutter doctor -v
        shell: bash
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
      - name: Build Flutter for ohos
        run: flutter build hap --release
        shell: bash
      - name: Package ohos build output
        run: cp ./ohos/entry/build/default/outputs/default/entry-default-unsigned.hap Kazumi_ohos_canary.hap
        shell: bash
      - name: Upload ohos outputs
        uses: actions/upload-artifact@v4
        with:
          name: ohos_outputs
          path: Kazumi_ohos_*.hap
